[tool.black]
line-length = 120

[tool.flake8]
max-line-length = 120
extend-ignore = ["E203", "W503", "F401", "F821"]
exclude = [".git", "__pycache__", ".venv"]

[tool.pylint]
max-line-length = 120
disable = ["C0114", "C0115", "C0116", "R0903"]
